baseURL = 'https://LArielOzjH.github.io/blogs/'
languageCode = 'zh-cn'
title = 'My Feishu Blog'
theme = 'PaperMod'

enableEmoji = true

[params]
author = 'Your Name'
description = "使用飞书+Hugo+Elog搭建的个人博客"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowFullTextinRSS = true

[params.homeInfoParams]
Title = "欢迎来到我的博客"
Content = "在飞书写作，自动同步发布"

ShowSearchPage = true

[menu]
[[menu.main]]
name = "首页"
url = "/"
weight = 10

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 20

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 30

[[menu.main]]
name = "搜索"
url = "/search/"
weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]
