baseURL = 'https://LArielOzjH.github.io/blogs/'
languageCode = 'zh-cn'
title = 'LArielO's LAB'
theme = 'PaperMod'

enableEmoji = true

[params]
author = 'LArielO'
description = "Personal Blogs in AI chips design"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowFullTextinRSS = true

[params.homeInfoParams]
Title = "Welcome to LArielO's Blog!"
Content = "for AI chips design"



ShowSearchPage = true

[menu]
[[menu.main]]
name = "Main"
url = "/"
weight = 10

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 30

[[menu.main]]
name = "About"  
url = "/about/"
weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]
